### ISSUE TITLE
RseNet-50 Pre-trained model and Featrues from images 

### ISSUE THREAD

**Issue by LiuShihHung** [lidq92/msmlTMIQA#2]
Hi @lidq92, your work is amazing! 
But I want to ask if you can provide pre-trained model and extracted features from images again.
Because the model and features in your BaiduNetDisk are not available. 

Thanks!!

**Comment by lidq92** [comment]
@LiuShihHung I checked the BaiduNetDisk links in README.md and they did work. 
Please try again with the correct link and its corresponding password (Note that the two URLs are not the same and their passwords are different).

**Comment by LiuShihHung** [comment]
Ok , thank you!
