### ISSUE TITLE
Some data in the ESPLLIVEHDRinfo.mat

### ISSUE THREAD

**Issue by LiuShihHung** [lidq92/msmlTMIQA#3]
Hi, I want to ask the index and ref_ids store in the ESPLLIVEHDRinfo.mat means. 

Thanks a lot!

**Comment by lidq92** [comment]
@LiuShihHung `index` is for train-test split and `ref_ids` is for the split of different "distortions" (algorithms).
See lines 51-67 of `QualityPrediction.m` for more details.
